language: python
python:
- "3.5.2"
install:
- pip install -r requirements.txt
- pip install pytest
- pip install pytest-cov
- pip install coveralls


script:
- pytest --cov=app app/tests/test_api.py
after_success:
- coveralls
