language: python
python:
- "3.5.2"
install:
- pip install -r requirements.txt
- pip install pytest
- pip install pytest-cov
- pip install coveralls


script:
- py.test API/test_api.py
- pytest --cov app
after_success:
- coveralls
